<a href="https://colab.research.google.com/github/Leonhard13/Leonhard13/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('alcohol_ANN.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[40 'Ciudad de Mexico' 'No' ... 0 0 'Hombre']
 [45 'Puebla' 'No' ... 0 2 'Hombre']
 [27 'Nuevo Leon' 'No' ... 4 4 'Hombre']
 ...
 [49 'Ciudad de Mexico' 'No' ... 0 0 'Mujer']
 [29 'Guerrero' 'No' ... 0 0 'Hombre']
 [31 'Estado De Mexico' 'No' ... 2 4 'Hombre']]


In [5]:
print(y)

[0 0 0 ... 0 0 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 14] = le.fit_transform(X[:, 14])
X[:, 2] = le.fit_transform(X[:, 2])
X[:, 3] = le.fit_transform(X[:, 3])

In [9]:
print(X)

[[40 'Ciudad de Mexico' 0 ... 0 0 0]
 [45 'Puebla' 0 ... 0 2 0]
 [27 'Nuevo Leon' 0 ... 4 4 0]
 ...
 [49 'Ciudad de Mexico' 0 ... 0 0 1]
 [29 'Guerrero' 0 ... 0 0 0]
 [31 'Estado De Mexico' 0 ... 2 4 0]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 2 0]
 [0.0 0.0 0.0 ... 4 4 0]
 ...
 [0.0 0.0 0.0 ... 0 0 1]
 [0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 2 4 0]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
218/218 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.6944
Epoch 2/100
218/218 [==============================] - 0s 2ms/step - loss: 0.2661 - accuracy: 0.9371
Epoch 3/100
218/218 [==============================] - 0s 1ms/step - loss: 0.2206 - accuracy: 0.9516
Epoch 4/100
218/218 [==============================] - 0s 2ms/step - loss: 0.2025 - accuracy: 0.9516
Epoch 5/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1932 - accuracy: 0.9516
Epoch 6/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1879 - accuracy: 0.9516
Epoch 7/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1846 - accuracy: 0.9516
Epoch 8/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1826 - accuracy: 0.9516
Epoch 9/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1812 - accuracy: 0.9516
Epoch 10/100
218/218 [==============================] - 0s 2ms/step - loss: 0.1800 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 


*   Age: 40 years old
*   Geography: Puebla
*   LGBTI: No
*   Indgena: No
*   R1: 1
*   R2: 0
*   R3: 1
*   R4: 1
*   R5: 1
*   R6: 0
*   R7: 1
*   R8: 0
*   R9: 0
*   R10: 0
*   sexo: Hombre

So, should we say goodbye to that customer ?

**Solution**

In [21]:
print(ann.predict(sc.transform([[40,0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,1,0,0,0]])) > 0.5)

ValueError: ignored

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

55/55 [==============================] - 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1663    8]
 [  70    0]]


0.9551981619758759